Search.appendIndex(
    [
                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Driver",
            "name": "Driver",
            "summary": "Class\u0020Driver",
            "url": "classes/Fundevogel-Thx-Drivers-Driver.html"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Driver\u003A\u003A__construct\u0028\u0029",
            "name": "__construct",
            "summary": "Constructor",
            "url": "classes/Fundevogel-Thx-Drivers-Driver.html#method___construct"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Driver\u003A\u003AfetchRemote\u0028\u0029",
            "name": "fetchRemote",
            "summary": "Fetches\u0020information\u0020from\u0020API\u0020endpoint",
            "url": "classes/Fundevogel-Thx-Drivers-Driver.html#method_fetchRemote"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Driver\u003A\u003AspreadLove\u0028\u0029",
            "name": "spreadLove",
            "summary": "Spreads\u0020love",
            "url": "classes/Fundevogel-Thx-Drivers-Driver.html#method_spreadLove"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Driver\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "Extracts\u0020raw\u0020data\u0020from\u0020input\u0020files",
            "url": "classes/Fundevogel-Thx-Drivers-Driver.html#method_extract"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Driver\u003A\u003Aextend\u0028\u0029",
            "name": "extend",
            "summary": "Retrieves\u0020additional\u0020package\u0020information",
            "url": "classes/Fundevogel-Thx-Drivers-Driver.html#method_extend"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Driver\u003A\u003A\u0024timeout",
            "name": "timeout",
            "summary": "Defines\u0020timeout\u0020for\u0020API\u0020requests\u0020\u0028in\u0020seconds\u0029",
            "url": "classes/Fundevogel-Thx-Drivers-Driver.html#property_timeout"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Driver\u003A\u003A\u0024userAgent",
            "name": "userAgent",
            "summary": "Controls\u0020\u0060User\u002DAgent\u0060\u0020header",
            "url": "classes/Fundevogel-Thx-Drivers-Driver.html#property_userAgent"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Driver\u003A\u003A\u0024pkgData",
            "name": "pkgData",
            "summary": "",
            "url": "classes/Fundevogel-Thx-Drivers-Driver.html#property_pkgData"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Driver\u003A\u003A\u0024lockFile",
            "name": "lockFile",
            "summary": "",
            "url": "classes/Fundevogel-Thx-Drivers-Driver.html#property_lockFile"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Node\\Npm",
            "name": "Npm",
            "summary": "Class\u0020Npm",
            "url": "classes/Fundevogel-Thx-Drivers-Node-Npm.html"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Node\\Npm\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "Extracts\u0020raw\u0020data\u0020from\u0020input\u0020files",
            "url": "classes/Fundevogel-Thx-Drivers-Node-Npm.html#method_extract"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Node\\Npm\u003A\u003Aextend\u0028\u0029",
            "name": "extend",
            "summary": "Retrieves\u0020additional\u0020package\u0020information",
            "url": "classes/Fundevogel-Thx-Drivers-Node-Npm.html#method_extend"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Node\\Npm\u003A\u003AformatURL\u0028\u0029",
            "name": "formatURL",
            "summary": "Makes\u0020Git\u0020repository\u0020notation\u0020human\u002Dreadable",
            "url": "classes/Fundevogel-Thx-Drivers-Node-Npm.html#method_formatURL"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Node\\Yarn",
            "name": "Yarn",
            "summary": "Class\u0020Yarn",
            "url": "classes/Fundevogel-Thx-Drivers-Node-Yarn.html"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Node\\Yarn\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "Extracts\u0020raw\u0020data\u0020from\u0020input\u0020files",
            "url": "classes/Fundevogel-Thx-Drivers-Node-Yarn.html#method_extract"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Node\\Yarn\u003A\u003AparseLockFileV1\u0028\u0029",
            "name": "parseLockFileV1",
            "summary": "Parses\u0020v1\u0020lockfile",
            "url": "classes/Fundevogel-Thx-Drivers-Node-Yarn.html#method_parseLockFileV1"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Node\\Yarn\u003A\u003AparseLockFileV2\u0028\u0029",
            "name": "parseLockFileV2",
            "summary": "Parses\u0020v2\u0020lockfile",
            "url": "classes/Fundevogel-Thx-Drivers-Node-Yarn.html#method_parseLockFileV2"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Node\\Yarn\u003A\u003AgetPackageNameV1\u0028\u0029",
            "name": "getPackageNameV1",
            "summary": "Determines\u0020package\u0020name\u0020\u0028v1\u0020only\u0029",
            "url": "classes/Fundevogel-Thx-Drivers-Node-Yarn.html#method_getPackageNameV1"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Node\\Yarn\u003A\u003AcleanString\u0028\u0029",
            "name": "cleanString",
            "summary": "Removes\u0020redundant\u0020characters\u0020from\u0020strings\u0020\u0028v1\u0020only\u0029",
            "url": "classes/Fundevogel-Thx-Drivers-Node-Yarn.html#method_cleanString"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Php\\Composer",
            "name": "Composer",
            "summary": "Class\u0020Composer",
            "url": "classes/Fundevogel-Thx-Drivers-Php-Composer.html"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Php\\Composer\u003A\u003Aextract\u0028\u0029",
            "name": "extract",
            "summary": "Extracts\u0020raw\u0020data\u0020from\u0020input\u0020files",
            "url": "classes/Fundevogel-Thx-Drivers-Php-Composer.html#method_extract"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Php\\Composer\u003A\u003Aextend\u0028\u0029",
            "name": "extend",
            "summary": "Retrieves\u0020additional\u0020package\u0020information",
            "url": "classes/Fundevogel-Thx-Drivers-Php-Composer.html#method_extend"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\ThankYou",
            "name": "ThankYou",
            "summary": "Class\u0020ThankYou",
            "url": "classes/Fundevogel-Thx-ThankYou.html"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\ThankYou\u003A\u003AveryMuch\u0028\u0029",
            "name": "veryMuch",
            "summary": "Gives\u0020back\u0020\u0026\u0020spread\u0020the\u0020love",
            "url": "classes/Fundevogel-Thx-ThankYou.html#method_veryMuch"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\ThankYou\u003A\u003AhaveFun\u0028\u0029",
            "name": "haveFun",
            "summary": "Enjoy\u0020the\u0020party\u0020\u0026\u0020have\u0020some\u0020fun",
            "url": "classes/Fundevogel-Thx-ThankYou.html#method_haveFun"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Utilities\\A",
            "name": "A",
            "summary": "",
            "url": "classes/Fundevogel-Thx-Utilities-A.html"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Utilities\\A\u003A\u003Afirst\u0028\u0029",
            "name": "first",
            "summary": "Returns\u0020the\u0020first\u0020element\u0020of\u0020an\u0020array",
            "url": "classes/Fundevogel-Thx-Utilities-A.html#method_first"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Utilities\\A\u003A\u003Alast\u0028\u0029",
            "name": "last",
            "summary": "Returns\u0020the\u0020last\u0020element\u0020of\u0020an\u0020array",
            "url": "classes/Fundevogel-Thx-Utilities-A.html#method_last"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Utilities\\A\u003A\u003Ajoin\u0028\u0029",
            "name": "join",
            "summary": "",
            "url": "classes/Fundevogel-Thx-Utilities-A.html#method_join"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Utilities\\Str",
            "name": "Str",
            "summary": "",
            "url": "classes/Fundevogel-Thx-Utilities-Str.html"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Utilities\\Str\u003A\u003Alength\u0028\u0029",
            "name": "length",
            "summary": "A\u0020UTF\u002D8\u0020safe\u0020version\u0020of\u0020strlen\u0028\u0029",
            "url": "classes/Fundevogel-Thx-Utilities-Str.html#method_length"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Utilities\\Str\u003A\u003Asplit\u0028\u0029",
            "name": "split",
            "summary": "Better\u0020alternative\u0020for\u0020explode\u0028\u0029\nIt\u0020takes\u0020care\u0020of\u0020removing\u0020empty\u0020values\nand\u0020it\u0020has\u0020a\u0020built\u002Din\u0020way\u0020to\u0020skip\u0020values\nwhich\u0020are\u0020too\u0020short.",
            "url": "classes/Fundevogel-Thx-Utilities-Str.html#method_split"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Utilities\\Str\u003A\u003Acontains\u0028\u0029",
            "name": "contains",
            "summary": "Checks\u0020if\u0020a\u0020str\u0020contains\u0020another\u0020string",
            "url": "classes/Fundevogel-Thx-Utilities-Str.html#method_contains"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Utilities\\Str\u003A\u003Altrim\u0028\u0029",
            "name": "ltrim",
            "summary": "Safe\u0020ltrim\u0020alternative",
            "url": "classes/Fundevogel-Thx-Utilities-Str.html#method_ltrim"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Utilities\\Str\u003A\u003Artrim\u0028\u0029",
            "name": "rtrim",
            "summary": "Safe\u0020rtrim\u0020alternative",
            "url": "classes/Fundevogel-Thx-Utilities-Str.html#method_rtrim"
        },                {
            "fqsen": "\\",
            "name": "\\",
            "summary": "",
            "url": "namespaces/default.html"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers",
            "name": "Drivers",
            "summary": "",
            "url": "namespaces/fundevogel-thx-drivers.html"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Node",
            "name": "Node",
            "summary": "",
            "url": "namespaces/fundevogel-thx-drivers-node.html"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Drivers\\Php",
            "name": "Php",
            "summary": "",
            "url": "namespaces/fundevogel-thx-drivers-php.html"
        },                {
            "fqsen": "\\Fundevogel\\Thx",
            "name": "Thx",
            "summary": "",
            "url": "namespaces/fundevogel-thx.html"
        },                {
            "fqsen": "\\Fundevogel",
            "name": "Fundevogel",
            "summary": "",
            "url": "namespaces/fundevogel.html"
        },                {
            "fqsen": "\\Fundevogel\\Thx\\Utilities",
            "name": "Utilities",
            "summary": "",
            "url": "namespaces/fundevogel-thx-utilities.html"
        }            ]
);
